"""Type stubs for pyscript.web module."""
from typing import Any, Sequence

class Element:
    """Represents a DOM element."""
    def __init__(self, element: Any) -> None: ...

    @property
    def textContent(self) -> str: ...

    @textContent.setter
    def textContent(self, value: str) -> None: ...

    @property
    def innerHTML(self) -> str: ...

    @innerHTML.setter
    def innerHTML(self, value: str) -> None: ...

    @property
    def value(self) -> str: ...

    @value.setter
    def value(self, value: str) -> None: ...

    def setAttribute(self, name: str, value: str) -> None: ...
    def getAttribute(self, name: str) -> str | None: ...
    def removeAttribute(self, name: str) -> None: ...
    def addEventListener(self, event_type: str, callback: Any) -> None: ...
    def removeEventListener(self, event_type: str, callback: Any) -> None: ...
    def appendChild(self, child: "Element") -> None: ...
    def removeChild(self, child: "Element") -> None: ...
    def remove(self) -> None: ...

class Page:
    """Provides access to the page DOM."""

    def find(self, selector: str) -> Element | None:
        """Find a single element by CSS selector."""
        ...

    def findAll(self, selector: str) -> Sequence[Element]:
        """Find all elements matching CSS selector."""
        ...

page: Page
